#!/usr/bin/env bash
# Probe script for Impermanence Setup.
#
# Detects drift between three sources of truth:
#   1. the Nix declaration   (modules/system/impermanence.nix)
#   2. the actual disk state (/persistent)
#   3. the installer seeding (installer/02-configure.sh)
#
# Parses ONLY the entries inside the `directories = [...]` / `files = [...]`
# blocks (comments stripped), so the output is not polluted by inline `#`
# notes the way a naive grep -A would be.

set -u

CONFIG_FILE="modules/system/impermanence.nix"
INSTALL_SCRIPT="installer/02-configure.sh"
PERSIST_TOP="/persistent"
USER="aul"

if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "missing $CONFIG_FILE — run this from the flake root." >&2
    exit 1
fi

echo "🔍 Scanning for Impermanence Drift..."
echo

# args: <block-name> e.g. directories|files
# Prints every quoted string found inside the named `x = [ ... ];` block,
# with inline `#` comments removed first.
entries_of() {
    local block="$1"
    awk -v block="$block" '
        $0 ~ "^[[:space:]]*" block "[[:space:]]*=[[:space:]]*\\[" { inblock=1; next }
        inblock && /]/ { inblock=0 }
        inblock {
            line=$0
            # drop the trailing inline comment (no persisted path contains '#')
            sub(/#.*$/, "", line)
            while (match(line, /"[^"]*"/)) {
                v = substr(line, RSTART+1, RLENGTH-2)
                if (v != "") print v
                line = substr(line, RSTART+RLENGTH)
            }
        }
    ' "$CONFIG_FILE"
}

# Resolve a declared entry to its real path under /persistent.
# Absolute entries (system dirs / files) map directly; relative entries map
# under the user's home.
resolve_path() {
    local entry="$1"
    if [[ "$entry" == /* ]]; then
        printf '%s' "$PERSIST_TOP$entry"
    else
        printf '%s' "$PERSIST_TOP/home/$USER/$entry"
    fi
}

PASS=0
FAIL=0

check_entry() {
    local type="$1" entry="$2"
    local real_path disk_ok
    real_path="$(resolve_path "$entry")"

    echo "--- Checking: $entry ---"

    if [[ "$type" == "directory" ]]; then
        test -d "$real_path" && disk_ok=1 || disk_ok=0
    else
        test -e "$real_path" && disk_ok=1 || disk_ok=0
    fi

    if [[ "$disk_ok" == "1" ]]; then
        echo "  ✅ Disk: Found at $real_path"
    else
        if [[ "$type" == "directory" ]]; then
            echo "  ❌ Disk: MISSING! Run: sudo mkdir -p $real_path && sudo chown $USER:users $real_path"
        elif [[ "$entry" == *ssh_host* ]]; then
            echo "  ❌ Disk: MISSING! Generate it, don't touch an empty file: sudo ssh-keygen -A -f /persistent (or copy an existing key in), then sudo chown $USER:users $real_path"
        else
            echo "  ❌ Disk: MISSING! Run: sudo mkdir -p \$(dirname $real_path) && sudo touch $real_path && sudo chown $USER:users $real_path"
        fi
        FAIL=$((FAIL+1))
    fi

    # Installer check: the entry must be seeded by the installer's mkdir list.
    # The installer uses "$TARGET/persistent/..." so grep for the path after
    # the persistent prefix is matched; fall back to a plain -F substring.
    # SSH host keys are generated by an installer loop (ssh_host_${kind}_key),
    # not named literally, so special-case the ssh_host_ prefix.
    if [[ "$entry" == *ssh_host* ]] \
        && grep -q -- 'ssh_host_.*_key' "$INSTALL_SCRIPT" 2>/dev/null; then
        echo "  ✅ Installer: Present in $INSTALL_SCRIPT (generated via ssh_host loop)"
    elif grep -Fq -- "$entry" "$INSTALL_SCRIPT" 2>/dev/null \
        || grep -qE -- "persistent.*${entry}" "$INSTALL_SCRIPT" 2>/dev/null; then
        echo "  ✅ Installer: Present in $INSTALL_SCRIPT"
    else
        echo "  ⚠️ Installer: MISSING! Update $INSTALL_SCRIPT to ensure fresh installs work."
        FAIL=$((FAIL+1))
    fi
    echo
    [[ "$disk_ok" == "1" ]] && PASS=$((PASS+1))
}

# --- Directories (system + per-user) ---
while IFS= read -r entry; do
    [[ -n "$entry" ]] && check_entry "directory" "$entry"
done < <(entries_of "directories")

# --- Files ---
while IFS= read -r entry; do
    [[ -n "$entry" ]] && check_entry "file" "$entry"
done < <(entries_of "files")

echo "=============================================="
echo "Checked: $((PASS+FAIL)) entries | OK: $PASS | problems: $FAIL"
[[ "$FAIL" -eq 0 ]] && echo "✅ No impermanence drift detected." || echo "❌ ${FAIL} problem(s) found — fix before next reboot."

# ------------------------------------------------------------
# Informational: btrfs metadata health (runbook warning #3)
# ------------------------------------------------------------
# Non-destructive and read-only — only REPORTS state, never runs a
# balance. Runbook warning #3: because the root subvol is snapshotted and
# deleted every boot, run `btrfs balance start -dusage=50 /` occasionally
# to reclaim fragmented metadata space. This block flags that case.
echo
echo "🔍 btrfs metadata health (informational; runbook warning #3)"

if ! command -v btrfs >/dev/null 2>&1; then
    echo "  ⏭  'btrfs' tool not installed — skipping."
elif [[ "$EUID" -ne 0 ]]; then
    echo "  ⏭  root required for btrfs usage stats — rerun with sudo to see this block."
else
    usage="$(btrfs filesystem usage / 2>/dev/null)"
    if [[ -z "$usage" ]]; then
        echo "  ⚠️  could not read btrfs usage stats."
    else
        printf '%s\n' "$usage" | grep -E '^(Device size|Data,|Metadata,|System,)' | sed 's/^/    /'
        # "Used" percentage inside "(…%)" of the metadata chunk line — a soft
        # proxy for metadata chunk pressure (real fragmentation needs a report).
        meta_pct="$(printf '%s\n' "$usage" | grep -E '^Metadata,' | grep -oP '\(\K[0-9.]+(?=%)' | sort -rn | head -1)"
        if [[ -n "$meta_pct" ]] && awk -v p="$meta_pct" 'BEGIN{exit !(p>80)}'; then
            echo "  ⚠️  metadata chunk usage ${meta_pct}% (>80%) — suggest: sudo btrfs balance start -dusage=50 /"
        else
            echo "  ✅ metadata chunk usage within normal bounds."
        fi
    fi
    bal="$(btrfs balance status / 2>/dev/null)"
    if [[ -n "$bal" ]] && grep -q 'running' <<<"$bal"; then
        echo "  ℹ️  a btrfs balance is currently running — nothing to do."
    else
        echo "  ℹ️  no btrfs balance in progress."
    fi
fi

exit 0