# Generated by the installer (stage 2) on 2026-08-28T09:11:49+00:00.
# Machine-specific hardware + filesystem layout produced by:
#   nixos-generate-config --root /mnt --show-hardware-config
# Do not hand-edit hardware values here; regenerate them instead.
# System policy lives in the flake (/mnt/persistent/home/aul/nixos-config).

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/nixos-crypt";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."nixos-crypt".device = "/dev/disk/by-uuid/5f24f78f-068b-4aee-84be-5e9093dcd74e";

  fileSystems."/nix" =
    { device = "/dev/mapper/nixos-crypt";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/persistent" =
    { device = "/dev/mapper/nixos-crypt";
      fsType = "btrfs";
      options = [ "subvol=@persistent" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0A1A-0CF9";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
