# Generated by the installer (stage 2) on 2026-08-28T09:11:49+00:00.
# Full-disk LUKS2 encryption declaration for auronix.
# The TPM2 auto-unlock slot is enrolled AFTER first boot (see stage 4's
# instructions); this block lets the initrd open the container, and with
# tpm2-device=auto present it does so hands-free. Slot 0 passphrase stays as
# the rescue key.
{ config, lib, ... }:
{
  boot.initrd.luks.devices."nixos-crypt" = {
    device = "/dev/disk/by-uuid/5f24f78f-068b-4aee-84be-5e9093dcd74e";
    allowDiscards = true;
    crypttabExtraOpts = [ "tpm2-device=auto" ];
  };
}
