# Generated by the installer (stage 2) on 2026-08-15T18:50:40+00:00.
# Machine-specific hardware + filesystem layout produced by:
#   nixos-generate-config --root /mnt --show-hardware-config
# Do not hand-edit hardware values here; regenerate them instead.
# System policy lives in the flake (/mnt/persistent/home/aul/nixos-config).

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e4f1133e-bbff-456f-a321-42b15823a133";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/e4f1133e-bbff-456f-a321-42b15823a133";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/persistent" =
    { device = "/dev/disk/by-uuid/e4f1133e-bbff-456f-a321-42b15823a133";
      fsType = "btrfs";
      options = [ "subvol=@persistent" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4F91-CD6F";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
